### ISSUE TITLE
centos 7 host has errors on managing /etc/libuser.conf

### ISSUE THREAD

**Issue by craigcomstock** [nickanderson/cfengine-security-hardening#12]
```
   error: No matched line to edit fields of for pattern '#+\s*crypt_style\s*=.*' in '/etc/libuser.conf'                                                       
   error: Errors encountered when actuating fields_edit promise '#+\s*crypt_style\s*=.*' 
```

**Comment by nickanderson** [comment]
`bundle agent default_encrypt_method_sha512` uses `set_variable_values_ini` from the standard library, this issue should be filed against the MPF and resolved there.

**Comment by nickanderson** [comment]
Actually, I can see that there is an existing issue for this: https://tracker.mender.io/browse/CFE-3866
