### ISSUE TITLE
update os is supported details

### ISSUE THREAD

**Issue by craigcomstock** [nickanderson/cfengine-security-hardening#24]
Ubuntu 22.04 is currently supported. Need to go through the items at https://github.com/nickanderson/cfengine-security-hardening/blob/master/compliance-report-os-is-vendor-supported/os-is-vendor-supported.json from data maybe at https://endoflife.date/

**Comment by nickanderson** [comment]
Oh, this kind of highlights an issue with the way the OS inventory works.

![image](https://user-images.githubusercontent.com/202896/206760156-dbb6ffb0-c7f7-440d-afb4-693fd5611c11.png)


The compliance rule is only for OS matching the major version number. But 22.10 will be EOL before 22.04 is EOL and both will match 22 for OS

**Comment by nickanderson** [comment]
@olehermanse ^ kind of begs for a change in how OS is reported.

**Comment by olehermanse** [comment]
@nickanderson I don't think we should change the "OS" inventory attribute, but we could add another attribute with the full version, or even the long name from `/etc/os-release` or whatever.
